### ISSUE TITLE
a few as-as errors

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#100]
- http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61c8116f1531d
- http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61c811a484900

**Comment by nschneid** [comment]
also "With shoes as wide as a forearm" is a with-absolute, so it should not be nmod

**Comment by amir-zeldes** [comment]
Fixed in dev, thanks!
