### ISSUE TITLE
PROPN/PRON followed by VBG is a frequent source of errors

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#104]
Reviewing the results of http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61e1e6bf56633, found these:

- with-absolutes (UniversalDependencies/UD_English-EWT#240): should have `nsubj` rather than `acl`:
  * with the Games being televised live
  * with Junius Ho defeating Lee Cheuk-yan
  * with Łódź campaigning and redesigning itself as an up-and-coming destination
- perception verbs: it is the action that is perceived, so pronoun should be `nsubj` I think
  * watch them fraying and frolicking
  * we could hear them singing
  * we notice it deviating slightly
  * You can see them visiting and talking
  * She thought she could hear Gomez laughing. 
  * You will also often see Thais doing a wai
  * A civic agent notices you noticing
  * (Why not `obj` and `xcomp`? Consider "Everyone was looking at me doing cartwheels": if the speaker is the only one doing cartwheels, "me doing cartwheels" is a constituent, not "at me". Cf. "It was me doing cartwheels that everyone was looking at." Even more obvious for a non-perception verb like "She doesn't object to me doing cartwheels".)
- others
  * photo of magician David Gish displaying magic props: David should be `nsubj` of displaying
  * File image of Space Shuttle Atlantis lifting off
  * Ronald McDonald showing how it's done
  * as well as it serving a deterrent purpose
  * Look at you being smart. 
  * Often I would find myself entering those crypts: entering should be `xcomp` not `acl`
  * recognising as legitimate the request of the Municipality of Livorno asking religious schools to pay property taxes: I think "asking" should attach to "request" as `acl`

**Comment by amir-zeldes** [comment]
Agreed on with absolutes and perception. Less sure about the nominals:

  * Photo of David (seems like the caption is primarily saying "it's a photo of this guy"; plus if we start interpreting nominals as 'perception' I don't know how to make a definitive guideline)
  * Same issue with image, Ronald

Agreed about:
  * look at you (perception verb)
  * serving
  * entering
  * request (syntactically ambiguous, but I read it like you)

**Comment by nschneid** [comment]
I think the cleft test helps:

- It's David displaying magic props that this photo is of
- *It's David that this photo displaying magic props is of
- *It's David that this photo is of displaying magic props

**Comment by nschneid** [comment]
Oh wait that just establishes it as a constituent; I guess the question is whether the head is "David" or "displaying". You could substitute a pronoun which really doesn't like to have modifiers:

* a photo of him displaying magic props

**Comment by nschneid** [comment]
xcomp I think. See UniversalDependencies/UD_English-EWT#292

**Comment by amir-zeldes** [comment]
Looking at that issue, I agree with the statements about "find", but "picture" seems wrong to me. For:

  * Picture yourself sitting on a warm, tropical beach

I don't feel any difference compared to:

  * See someone sitting on a warm, tropical beach

The latter is definitely ccomp, right? If so, how is "picture" different from "see"? Whereas "find yourself" really just means being there, not finding some complex predicate.

**Comment by nschneid** [comment]
I'm not sure it's different—I think there's gray area with some of these constructions.

**Comment by amir-zeldes** [comment]
Hm, OK, we don't actually have a case of this verb in GUM right now, but in any case I'll make the "find" instances be xcomp. Thanks!
