### ISSUE TITLE
Some possessive pronoun issues

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#105]
- [query 1](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61e328cb0728c&clustering=O.lemma)
- [query 2](http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=61e3298be38e0) (a couple of these are errors)

**Comment by amir-zeldes** [comment]
OK, I saw one error in q2 (mother says), just fixed it - is there anything wrong in q1?

**Comment by nschneid** [comment]
Also "gave her strength" in q2. In q1 most of them have the wrong xpos or are missing `Poss=Yes`, `Typo=Yes` etc.
