### ISSUE TITLE
XPOS for currency symbols

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#115]
EWT uses `$`: http://universal.grew.fr/?custom=62c96c35a8333

GUM uses `SYM`: http://universal.grew.fr/?custom=62c96c75450d9

(The UPOS is `SYM` for both.)

**Comment by amir-zeldes** [comment]
Interesting - I can correct this, but should we do this for all currencies, or just USD? PTB does not seem to have precedents, though OntoNotes has tokens `#` which seem to stand for the UK pound sign (I'm pretty sure it must've been the actual pound symbol in the underlying texts)

**Comment by nschneid** [comment]
I think `$` is supposed to be the tag for currency symbols generally. I see it documented [here](https://clear.colorado.edu/compsem/documents/treebank_guidelines.pdf#subsection.3.8). It may not be used in all Penn corpora.

**Comment by amir-zeldes** [comment]
OK, I have some other things to take care of, but I will put this on the agenda for GUM.
