### ISSUE TITLE
RST guidelines links broken on website

### ISSUE THREAD

**Issue by nnkennard** [amir-zeldes/gum#117]
Hello, hope this is the correct place for this issue!

On the [Annotations](https://gucorpling.org/gum/annotations.html) page, the links to guidelines for RST seem to be broken:
* https://gucorpling.org/gum/RSTDT-tagging-ref-manual.pdf (which I guess might be the same as [this document](https://www.isi.edu/~marcu/discourse/tagging-ref-manual.pdf)?)
* https://corpling.uis.georgetown.edu/wiki/doku.php?id=gum:rst

Thank you!

**Comment by nnkennard** [comment]
Thank you so much! Looking forward to possibly using the guidelines to annotate my own data.

**Comment by amir-zeldes** [comment]
Thanks for finding that @lgessler ! I should point out however that GUM guidelines are constantly evolving. The guidelines in that snapshot probably correspond to the data in GUM V7, but there have been some substantial changes in V8, which is what you see in GitHub right now, including some new discourse relations and guidelines for assigning them.

To see the current inventory of relations and their descriptions, you can look at the UD GUM repo, which is up to date with GUM V8 data:

https://github.com/UniversalDependencies/UD_English-GUM/#rst-discourse-trees

**Comment by amir-zeldes** [comment]
The guidelines wiki is now back online at a new URL using a new interface:

https://wiki.gucorpling.org/en/gum/rst

There might still be some bugs due to the migration from Dokuwiki to Wikijs, but the contents should be there - if anything looks broken or missing, please open another issue.
