### ISSUE TITLE
Double ccomp/xcomp errors

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#129]
http://universal.grew.fr/?custom=63cf099b0409d

**Comment by amir-zeldes** [comment]
Thanks, but I think these already came up in another issue and have been fixed in dev:

https://github.com/amir-zeldes/gum/blob/dev/_build/src/dep/GUM_bio_holt.conllu#L1113

They're just waiting for the GUM v9 release to propagate to the UD repo.
