### ISSUE TITLE
Several sentence-initial "So" mistagged as RB/advmod instead of UH/discourse

### ISSUE THREAD

**Issue by lgessler** [amir-zeldes/gum#131]
https://gucorpling.org/annis/#_q=IlNvIg&_c=R1VN&cl=5&cr=5&s=0&l=10

**Comment by amir-zeldes** [comment]
Unfortunately, not all of these are wrong - you can have So/RB if it is substitutable with therefore. For example in GUM_interview_herrick:

  * I recognized that the wiki model had the potential to build the how - to resource the world really needs . **So/RB** I decided to sell eHow and use the proceeds to build wikiHow .

I'm sure the query contains some errors, but someone would have to go through these manually to sort them out...

**Comment by amir-zeldes** [comment]
Yes, I would assume that. I mean, initially I was going to say it depends on the previous sentence, but it looks like it's the absolute first sentence in the recording:

https://www.linguistics.ucsb.edu/sites/secure.lsit.ucsb.edu.ling.d7/files/sitefiles/research/SBC/SBC025.trn

So it's 100% ture POS tag may be lost to time ;)

**Comment by lgessler** [comment]
Just combed through all the results in ANNIS, and I think these ones are suspicious:

* I get it , yeah . Oh I know . **So/RB** what about you Sherry, are you gon na put lemon in your hot tea ? ([GUM_conversation_family](https://github.com/amir-zeldes/gum/blob/master/xml/GUM_conversation_family.xml#L1106))
* So/UH Carolyn was really happy . **So/RB** , yeah because C- – ([GUM_conversation_family](https://github.com/amir-zeldes/gum/blob/master/xml/GUM_conversation_family.xml#L1908))
* I literally started the vlog and I was like , " hey ! " . And now we did yoga ! **So/RB** now we did yoga . ([GUM_vlog_college](https://github.com/amir-zeldes/gum/blob/dev/_build/src/xml/GUM_vlog_college.xml#L782))
* Good morning ! **So/RB** we just slept in today [...] ([GUM_vlog_hiking](https://github.com/amir-zeldes/gum/blob/dev/_build/src/xml/GUM_vlog_hiking.xml#L9))
* How To Flirt Through Instant Messaging **So/RB** you want to flirt with a guy or gal on MSN , AIM , Facebook Chat, or any other instant messaging service [...] ([GUM_whow_flirt](https://github.com/amir-zeldes/gum/blob/dev/_build/src/xml/GUM_whow_flirt.xml#L14))

**Comment by amir-zeldes** [comment]
All of these look like UH to me, thanks! I was about to say that we will get this info for free once connective annotation is done for signaling (UH should not be a DM), but now that you've gone over them I can just fix them for this release already!
