### ISSUE TITLE
Suspicious treatment of "more than"

### ISSUE THREAD

**Issue by lgessler** [amir-zeldes/gum#137]
https://gucorpling.org/annis/#_q=bGVtbWE9ImJlIi4ibW9yZSIuInRoYW4i&_c=R1VN&cl=5&cr=5&s=0&l=10

4th hit has an nmod out of more/RBR which I think can't be acceptable

**Comment by amir-zeldes** [comment]
The 4th one is definitely wrong. The second uses fixed for more-than modifying a quantity, which is canonical, and the third is more borderline (not sure if 'sufficient' is a quantity in this respect). I'll definitely fix 4.

**Comment by amir-zeldes** [comment]
Looks like I had already caught it in 6622892 (and the buildbot will now catch such cases too)
