### ISSUE TITLE
Units of measure (mL, km, cm, ...) inconsistently tagged wrt number

### ISSUE THREAD

**Issue by lgessler** [amir-zeldes/gum#138]
See ANNIS search for `/mL|mg|cm|km|mi‎/`--inconsistenly tagged as `NN` and `NNS`. Lemmas are also worth checking

**Comment by amir-zeldes** [comment]
Thanks for reporting - but actually, after going through the hits it seems to me that there is only one error (in GUM_whow_chicken). All of the others only vary in contexts where the spelled out variant would in fact be singular/plural, for example:

  * about 500 miles (800 km/NNS)
  * the surrounding 2 km/NN circumference of the monument

As a compound modifier, the spelled out 'kilometer' would also have the singular form, so it seems reasonable to tag these cases differently. Will fix the one error in whow_chicken though!
