### ISSUE TITLE
some verb errors

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#148]
WARN: VBZ should correspond with Number=Sing in GUM_news_iodine-39 @ token 36
WARN: VBZ should correspond with Person=3 in GUM_news_iodine-39 @ token 36

- Wrong feats

WARN: VBZ should correspond with Person=3 in GUM_whow_procrastinating-32 @ token 9

- Wrong feats

WARN: tag VBN should have lemma distinct from word form in GUM_interview_messina-67 @ token 20 (broadcast -> know) en_gum-ud-train.conllu

- Typo. Xpos should be `VBD`?

WARN: tag VBN should have lemma distinct from word form in GUM_speech_data-10 @ token 10 (ROOT -> disappear) en_gum-ud-train.conllu

- There is a complicated grammatical correction here. Maybe ignore the warning

WARN: function nsubj:pass should not be the child of pos VBD in GUM_speech_floyd-33 @ token 3 (was -> I) en_gum-ud-train.conllu
WARN: Passive verb with lemma 'be' should be VBN in GUM_speech_floyd-33

- Speech repair. Both "was" tokens should be AUX

WARN: tag VBD should have lemma distinct from word form in GUM_textbook_alamo-24 @ token 5 (ROOT -> forbade) en_gum-ud-train.conllu
WARN: tag VBN should have lemma distinct from word form in GUM_textbook_anthropology-9 @ token 7 (winking -> related) en_gum-ud-train.conllu
WARN: tag VBD should have lemma distinct from word form in GUM_vlog_mermaid-12 @ token 1 (ROOT -> Saw) en_gum-ud-train.conllu
! rare lemma set for sat/VBD in GUM_conversation_lambada-59, GUM_conversation_lambada-60 (majority: sit)
! rare lemma understan- for understand/VB in GUM_conversation_gossip-65 (majority: understand)

- Incorrect lemmas

WARN: Passive verb with lemma 'Rated' should be VBN in GUM_voyage_cleveland-4

- In a proper name. "Rated" should be VERB/lemma "rate" at least

WARN: tag VBN should have lemma distinct from word form in GUM_whow_languages-21 @ token 4 (term -> complete) en_gum-ud-train.conllu

- If corrected from "completed" to "complete", should be ADJ/JJ?

**Comment by amir-zeldes** [comment]
will fix, thanks
