### ISSUE TITLE
Which annotation tools or NLP packages to make the corpus GUM.zip?

### ISSUE THREAD

**Issue by fishfree** [amir-zeldes/gum#153]
I'm quite wondering how you guys made such a great [corpus](https://github.com/amir-zeldes/gum/blob/master/annis/GUM.zip), which supports so many features such as KWIC / grid / UD / morphology / constituents / coreference / RST?

Salute!

**Comment by amir-zeldes** [comment]
Thanks for the kind words - the basic creation process of the initial corpus (which was only 10% of the current data) is described in [this article](https://link.springer.com/content/pdf/10.1007/s10579-016-9343-x.pdf?pdf=button). Many of the tools used in that original version were replaced over the years as the corpus has grown and we developed our own tools. Specifcially:

  * Document structure/tagging: Oxygen -> [GitDox](https://gucorpling.org/gitdox/)
  * Entities/coref: WebAnno -> Inception -> GitDox [Spannotator](https://gucorpling.org/gitdox/spannotator.html)
  * RST: RSTTool -> [rstWeb](https://gucorpling.org/rstweb/info/)

The constituent parses are indeed NLP output from a model which takes gold POS tags as a feature, and some projected gold information from the manually annotated dependencies. The parser is [Mrini et al.'s](https://aclanthology.org/2020.findings-emnlp.65/). Hope that helps!

**Comment by fishfree** [comment]
@amir-zeldes I tried GitDox according the [README ](https://github.com/gucorpling/gitdox)by running:
```
sudo git clone https://github.com/gucorpling/gitdox /var/www/gitdox
sudo chown -R www-data:www-data /var/www/gitdox
docker run -dit --restart unless-stopped --name gitdox -v /var/www/gitdox:/var/www/html -p 8082:80 gucorpling/gitdox gitdox

```
When I access /admin.py 500 Internal Server Error.

**Comment by amir-zeldes** [comment]
That is just the error from the web server meaning something went wrong; if you can get the actual error from the logs we could try to figure it out (it could be anything from incorrect permissions to a missing dependency to anything else...)
