### ISSUE TITLE
compound should be nmod:poss

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#156]
"a Dillard's bag" https://universal.grew.fr/?custom=649b516980727

**Comment by amir-zeldes** [comment]
Thanks for reporting, but I think that's correct - "Dillard's" is the name of a store, so while "'s" is `case` (within a name), the a "Dillard's bag" is still a compound IMO.

**Comment by nschneid** [comment]
Yeah this is one of the quirky uses of possessive marking...I guess we can say it's a name/MWE phenomenon and what looks superficially like a possessive marking on a nominal modifier does not actually indicate that it functions as a *possessive* modifier.

I would feel more comfortable if the logic was made explicit somehow—maybe something to keep in mind for an MWE or constructional layer.
