### ISSUE TITLE
Wrong entity type for ages

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#157]
Should be `abstract`, but labeled `time` in:

- I need all my courage to die at **twenty**!) [bio_galois-42]
- And then she told her that, she didn't outgrow it until she was **five** or something? [conversation_family-174]
- She was **five** or something? [conversation_family-178]
- the children, who were over the age of **six** at the time of collection [academic_implicature-2]

**Comment by amir-zeldes** [comment]
Thanks for reporting! The last one shouldn't even be a span IMO (there is only one mention in "the age of six", which is already abstract; there shouldn't be a nested mention)
