### ISSUE TITLE
VERBs in nominal functions

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#162]
Several of the hits at https://universal.grew.fr/?custom=651183e239657 are errors. (Some, like "the following/VERB", are OK I guess.)

The validator checks only VVG verbs:
https://github.com/amir-zeldes/gum/blob/b153503b71b727a65d44f89ecbfd9146dd73911f/_build/utils/validate.py#L781-L783

It might be a good idea to update this to cover all verbs. Here's my [revised](https://github.com/UniversalDependencies/UD_English-EWT/commit/56c86cfeb672f10a570a7f0ad50947c06f2290a2) implementation for EWT:

https://github.com/UniversalDependencies/UD_English-EWT/blob/56c86cfeb672f10a570a7f0ad50947c06f2290a2/not-to-release/tools/neaten.py#L470-L472

**Comment by amir-zeldes** [comment]
Good catch, thanks - about half of those are errors, the rest are either nominalized (like 'following', which I take it should retain the POS like nominalized ADJ in "the poor" etc.), or embedded titles headed by a verb (which I take it should keep the nominal deprel and the verbal POS). Will fix.
