### ISSUE TITLE
ADV as amod

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#163]
Most if not all of these look invalid: https://universal.grew.fr/?custom=65134aa27b5a6

I added a warning to neaten.py.

**Comment by amir-zeldes** [comment]
OK, should be fixed, except cases that involve a phrasal compound (POS is token-wise, deprel can still be amod indicating the attachment of the whole compound - e.g. "once/RB/amod -in-a-generation/obl crisis")
