### ISSUE TITLE
validate.py bugs

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#166]
UniversalDependencies/UD_English-EWT@bcc83a4 updates neaten.py to fix a couple of issues inherited from validate.py:

https://github.com/amir-zeldes/gum/blob/b153503b71b727a65d44f89ecbfd9146dd73911f/_build/utils/validate.py#L710

- checks for `auxpass` instead of `aux:pass`

https://github.com/amir-zeldes/gum/blob/b153503b71b727a65d44f89ecbfd9146dd73911f/_build/utils/validate.py#L788-L791

- has functions from Stanford Dependencies
- will never be triggered in practice because `not` on line 790 scopes only over first conjunct

**Comment by amir-zeldes** [comment]
Fixed, thanks for catching!
