### ISSUE TITLE
VBN with "be" as plain aux or cop and no passive dependents

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#167]
https://universal.grew.fr/?custom=653574472c6a6

At least some of these are lemma errors (_'s_ whose lemma should be "have").

Others seem to assume an ADJ analysis in one part of the tree but a passive VERB analysis in another.

**Comment by amir-zeldes** [comment]
Remaining cases are kinds of :outer or compounds where the agent is expressed as a compound modifier.
