### ISSUE TITLE
A couple errors related to it-expletives/clefts/extrapositions

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#178]
From examining https://universal.grew.fr/?custom=6593a69b24161

- It took a few days good brushing to get it off.
   * Extraposition. csubj attachment is wrong (head is "brushing", should be "took")
- It was the Olmec who worshipped a rain god, a maize god, and the feathered serpent so important in the future pantheons of the Aztecs (who called him Quetzalcoatl) and the Maya (to whom he was Kukulkan). 
   * Looks like an it-cleft to me, so acl:relcl should be advcl:relcl

**Comment by amir-zeldes** [comment]
Fixed, thanks!
