### ISSUE TITLE
passive VERBs with copulas: should actually be ADJ?

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#182]
https://universal.grew.fr/?custom=653dccf9ed623

Looks like these are mostly in new genres. 

Here's the neaten.py code for validating passives:
https://github.com/UniversalDependencies/UD_English-EWT/blob/7d3e96c3331620edcf78e332e892686fc9530afa/not-to-release/tools/neaten.py#L336-L401

**Comment by amir-zeldes** [comment]
huh.. Thanks for reporting - I thought we had code to catch these, but I notice the script makes them all into nsubj:outer, so I'm guessing the script checks only for plain nsubj or something. I'll investigate when I get a chance!

**Comment by amir-zeldes** [comment]
OK, true issues are fixed, and as discussed offline, compound cases like "self inflicted" or "tailor made" are allowed VBN + cop. I've also added ExtPos to fixed as discussed, we could consider whether these should get ExtPos as well. The GUM validator is updated and allows these exceptions.
