### ISSUE TITLE
case/det/mark attaching in unusual environment

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#184]
- [x] structural issue under `flat`: https://universal.grew.fr/?custom=660c0592c0e6f
- [x] unusual environment for `mark`: https://universal.grew.fr/?custom=660c07ba3fa8f
   * The `advmod`, `obl:agent`, and `obl:tmod` ones look like errors. Not sure about the others.
- [x] `case`/`det` under `amod`: https://universal.grew.fr/?custom=661af315db099

**Comment by amir-zeldes** [comment]
Fixed and added to GUM validator, thanks!
