### ISSUE TITLE
Spurious VerbForm=Inf

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#193]
A bunch of these. Queries at UniversalDependencies/UD_English-EWT#284 can be a starting point (with manual review).

Interesting genre-specific cases arise, like "see" in citations (is that imperative?).

**Comment by amir-zeldes** [comment]
Yeah, I had a look and corrected the obvious ones (VV tag for VVP). Should propagate on release. I think "see" is imperative there.
