### ISSUE TITLE
error thrown by build_gum.py

### ISSUE THREAD

**Issue by cainesap** [amir-zeldes/gum#33]
Hi, thanks for this great resource!
A couple of comments for running `python build_gum.py`.
Firstly, the user needs to cd to the `_build` directory, otherwise `_build/src` is not found from the root dir; this could be mentioned in the README maybe?
Second, there's an encoding error from `utils/stanford2ud.py` (using Python 2 on Mac 10.13). The fix is to add the following two lines at the top of the file:
```
#!/usr/bin/python
# -*- coding: utf-8 -*-
```
As in https://www.python.org/dev/peps/pep-0263
best, Andrew

**Comment by amir-zeldes** [comment]
Good point, thanks for reporting!

Incidentally Python 2 won't work with stanford2ud.py since it relies on udapi, which doesn't support Python 2. If you run build_gum.py -u (to generate UD), you should get a warning.
