### ISSUE TITLE
UD conversion errors

### ISSUE THREAD

**Issue by amir-zeldes** [amir-zeldes/gum#35]
UD conversion error list, examples added as comments:

- [x] Subject relative nsubj with 'which' becomes 'obj' (turns out to be related to xcomp rule)
- [x] Subject nsubj -> obj in copula environment (same issue as the above)
- [x] Adverbial copula predicates should be treated like PP predicates (currently 'be' is left as the root in "it is here" but not in "it is in the house", see real example below)
- [x] Consider adding a rule: "and" with func `dep` -> `reparandum` (only occurs once)
- [x] Bug affecting coordinated prepositions (conj still comes out of the prep -> case; should come from lexical item)
- [x] Handle PP root with modifiers

**Comment by amir-zeldes** [comment]
Example of adverbial copula predicate:
```
1	These	_	DT	_	_	2	det	_	_
2	people	_	NNS	_	_	7	nsubj	_	_
3	can	_	MD	_	_	7	aux	_	_
4	be	_	VB	_	_	7	cop	_	_
5	a	_	DT	_	_	7	det	_	_
6	great	_	JJ	_	_	7	amod	_	_
7	source	_	NN	_	_	0	root	_	_
8	of	_	IN	_	_	7	prep	_	_
9	potential	_	JJ	_	_	10	amod	_	_
10	pain	_	NN	_	_	8	pobj	_	_
11	,	_	,	_	_	0	punct	_	_
12	and	_	CC	_	_	7	cc	_	_
13	this	_	DT	_	_	14	det	_	_
14	article	_	NN	_	_	15	nsubj	_	_
15	is	_	VBZ	_	_	7	conj	_	_
16	here	_	RB	_	_	15	advmod	_	_
17	to	_	TO	_	_	18	aux	_	_
18	help	_	VV	_	_	15	xcomp	_	_
19	you	_	PP	_	_	20	nsubj	_	_
20	sort	_	VV	_	_	18	xcomp	_	_
21	the	_	DT	_	_	22	det	_	_
22	arrogant	_	JJ	_	_	20	dobj	_	_
23	from	_	IN	_	_	20	prep	_	_
24	the	_	DT	_	_	25	det	_	_
25	not-so-arrogant	_	JJ	_	_	23	pobj	_	_
26	.	_	SENT	_	_	0	punct	_	_
```

**Comment by amir-zeldes** [comment]
Example of coordinated preposition problem:
```
1	Do	_	VVP	_	_	3	aux	_	_
2	n't	_	RB	_	_	3	neg	_	_
3	eavesdrop	_	VV	_	_	0	root	_	_
4	,	_	,	_	_	0	punct	_	_
5	but	_	CC	_	_	9	cc	_	_
6	when	_	WRB	_	_	9	advmod	_	_
7	they	_	PP	_	_	9	nsubj	_	_
8	're	_	VBP	_	_	9	aux	_	_
9	talking	_	VVG	_	_	18	advcl	_	_
10	to	_	TO	_	_	9	prep	_	_
11	you	_	PP	_	_	10	pobj	_	_
12	or	_	CC	_	_	10	cc	_	_
13	to	_	TO	_	_	10	conj	_	_
14	those	_	DT	_	_	13	pobj	_	_
15	around	_	IN	_	_	14	prep	_	_
16	you	_	PP	_	_	15	pobj	_	_
17	,	_	,	_	_	0	punct	_	_
18	listen	_	VV	_	_	3	conj	_	_
19	to	_	TO	_	_	18	prep	_	_
20	them	_	PP	_	_	19	pobj	_	_
21	.	_	SENT	_	_	0	punct	_	_
```

**Comment by loganpeng1992** [comment]
Another example of coordination of prep:


1	The	_	DT	_	_	2	det	_	_
2	purpose	_	NN	_	_	0	root	_	_
3	of	_	IN	_	_	2	prep	_	_
4	the	_	DT	_	_	5	det	_	_
5	author	_	NN	_	_	3	pobj	_	_
6	and	_	CC	_	_	3	cc	_	_
7	of	_	IN	_	_	3	conj	_	_
8	the	_	DT	_	_	9	det	_	_
9	translator	_	NN	_	_	7	pobj	_	_
10	:	_	:	_	_	0	punct	_	_

**Comment by loganpeng1992** [comment]
prep + pcomp + pobj with 'based on' which should not be an advcl (I guess)

1	Here	_	RB	_	_	3	advmod	_	_
2	he	_	PP	_	_	3	nsubj	_	_
3	identifies	_	VVZ	_	_	0	root	_	_
4	two	_	CD	_	_	6	num	_	_
5	basic	_	JJ	_	_	6	amod	_	_
6	orientations	_	NNS	_	_	3	dobj	_	_
7	in	_	IN	_	_	6	prep	_	_
8	translating	_	VVG	_	_	7	pcomp	_	_
9	based	_	VVN	_	_	3	prep	_	_
10	on	_	IN	_	_	9	pcomp	_	_
11	two	_	CD	_	_	13	num	_	_
12	different	_	JJ	_	_	13	amod	_	_
13	types	_	NNS	_	_	10	pobj	_	_
14	of	_	IN	_	_	13	prep	_	_
15	equivalence	_	NN	_	_	14	pobj	_	_
16	:	_	:	_	_	0	punct	_	_

**Comment by amir-zeldes** [comment]
prep + pcomp seems wrong here. I think 'based on' should be SD vmod + prep, which would solve the problem (alternatively it's prep + mwe, but I think we can literally see this as a verb).

**Comment by amir-zeldes** [comment]
Example of PP root with modifiers:
```
1	Is	_	VBZ	_	_	4	cop	_	_
2	it	_	PP	_	_	4	nsubj	_	_
3	always	_	RB	_	_	4	advmod	_	_
4	about	_	IN	_	_	0	root	_	_
5	them	_	PP	_	_	4	pobj	_	_
6	?	_	SENT	_	_	0	punct	_	_
```
