### ISSUE TITLE
Fix possessive genitive 's not attached to markable

### ISSUE THREAD

**Issue by amir-zeldes** [amir-zeldes/gum#46]

**Comment by amir-zeldes** [comment]
Suggested solution:

  * Read POS tags for each file from middle column of src/xml/*.xml, and keep them in a document-wise dictionary
  * Now read each corresponding file in src/tsv/*.tsv:
    * For each row, collect entity and infstat information (you can ignore the coref columns, you won’t need to change them as coref is marked only on the first token of each span, which ‘s never is)
    * For each row, keep track of the unique entity IDs that appear in it, e.g. person[4] or place[56]
    * Note that if an entity spans only one token, it receives no ID in WebAnno, but only one of these is possible in a row
  * Now comes the editing:
    * Go over the rows that correspond to pos tag POS (possessive s)
    * Get the set difference of entities between this row and the preceding row
      * If the preceding row contains any entity IDs that the POS row does not, duplicate the entity and infstat annotation for that entity and add those to the (pipe delimited) annotations on the POS row
      * If the previous row contained a single-token entity, this will mean editing both rows and inventing a new unique entity ID to unite them (an arbitrary high number, such as 1000, should work fine)

**Comment by lgessler** [comment]
Should be done with 667fe81. I inspected the output running it on non-dry mode (`-g` running from `build_gum.py`) and it looks good to me, though you might want to take a look too.
