### ISSUE TITLE
SyntaxError in propagate.py

### ISSUE THREAD

**Issue by dlukes** [amir-zeldes/gum#48]
Trying to build the corpus with `build_gum.py` including Reddit data, I run into a `SyntaxError` in `propagate.py` which is caused by a byte which is neither ASCII (which is a problem for Python 2) nor UTF-8 (which is a problem for Python 3):

```
$ python3 _build/utils/propagate.py
  File "_build/utils/propagate.py", line 107
SyntaxError: Non-UTF-8 code starting with '\x91' in file _build/utils/propagate.py on lin
e 107, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
$ python _build/utils/propagate.py
  File "_build/utils/propagate.py", line 107
SyntaxError: Non-ASCII character '\x91' in file _build/utils/propagate.py on line 107, bu
t no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Inspecting the file in Vim, there are more bytes like this beyond this point. Perhaps a `coding` declaration is missing at the top of the file?

**Comment by amir-zeldes** [comment]
That's strange, my Python 2.7 and 3.5 don't complain about it, maybe something to do with the system's native codepage. In any case yes, I can add `# -*- coding: utf-8 -*-` to the top.

If you want to have UD syntax generation, you'll need to use Python 3 (since the script uses udapi, which doesn't support Python 2)

**Comment by amir-zeldes** [comment]
My local machine is Windows, but the characters are definitely utf-8, not cp1252. I just tested the code after adding the coding statement (committed to dev branch) under Red Hat Linux with Python 3.5 and it works fine. Have you tested with the coding statement added?

**Comment by dlukes** [comment]
Sorry for being pedantic about this, but the issue wasn't fixed by adding the `coding` comment.  Commit 536b8e0 not only added that comment, it also changed the lines with the offending bytes (which I must insist were not valid UTF-8) -- this is part of the diff shown by `git show  536b8e0`:

```diff
@@ -104,8 +106,8 @@ def enrich_dep(gum_source, gum_target, reddit=False):
                                        current_sic = False
                        elif len(line)>0:  # Token
                                fields = line.split("\t")
-                               word = fields[0].replace("`","'").replace("<91>","'").replace("<92>","'")
-                               word = word.replace('<93>','"').replace("<94>",'"')
+                               word = fields[0].replace("`","'").replace("‘","'").replace("’","'")
+                               word = word.replace('“','"').replace("”",'"')
                                word_pos = fields[1].replace('"',"''")
                                tok_num += 1
                                if word == "(":
```

The numbers in the angle brackets (`<91>` etc.) represent bytes `0x91` etc., `0b10010001` etc. in binary. Bytes with a leading `1` only exist as part of multi-byte sequences in UTF-8, they cannot stand on their own between two "ASCII" bytes (i.e. bytes with a leading `0`).

In CP1252, bytes `0x91` etc. stand for [opening and closing simple and double smart quotes](https://en.wikipedia.org/wiki/Windows-1252). Commit 536b8e0 replaced these bytes with multi-byte sequences encoding these same characters in UTF-8. **If this is not what was originally intended in the code, the relevant lines need to be amended.** (Though I guess this *is* what was intended, since the result is that smart quotes get replaced with corresponding plain quotes, which seems reasonable.)

The `coding` comment is necessary for Python 2 (which expects source files to be ASCII by default). By contrast, Python 3 only accepts source files in UTF-8, irrespective of any `coding` comments.

Again, sorry for dwelling on this, but I thought it worth clarifying in case this should happen again :) Other than that, yes, 536b8e0 fixes the issue (for the reasons spelled out above).

**Comment by amir-zeldes** [comment]
Wow, that's really weird - and not pedantic at all, thanks for clarifying. What's strangest about this is that my Git client does not show any diff between the previous version of these glyphs and the current one. I have to assume it is somehow mediating encodings by itself and not telling me about it. It's supposed to do this if it has `\r` newlines, but not for text characters...

As for how the glyph got in there in the first place, that's also a bit of a mystery. The characters almost certainly got into the script by being pasted in from a GUM text, which should be utf8. The script may have been edited by some student RAs with various OSs, including Windows, so it's also possible someone else somehow introduced the glyphs, and the Git client 'undid' this on pull on my machine, then they got 'fixed' when I pushed. 

This is all theoretical though - personally I have no recollection of every swapping them out. In short, if it works now, then yes - that's the intention! The *.xml files will still always have the last say in terms of what the actual document texts are - all other representations of the base text are propagated from them.

**Comment by dlukes** [comment]
> my Git client does not show any diff between the previous version of these glyphs and the current one

FWIW, GitHub renders the diff with the same glyphs (smart quotes) on the removed and added lines: https://github.com/amir-zeldes/gum/commit/536b8e0c0bc1354ad1a3982cb389d319e1b75740#diff-c1301ceb687f7c875cf9f1b3f96dac37L107 Which is not really helpful for diagnosing the issue either :)

I guess the reason is they try to show meaningful glyphs (not just byte placeholders) for any text encoding, as opposed to e.g. assuming UTF-8 (which is what the `git` CLI executable can do in a UTF-8-encoded terminal, and just render unexpected bytes as placeholders).
