### ISSUE TITLE
"how"-modified acl/advcl 

### ISSUE THREAD

**Issue by lgessler** [amir-zeldes/gum#67]
The dependency trees for these are [wrong in a number of instances](https://corpling.uis.georgetown.edu/annis/#_q=cG9zPSJJTiIgLiAiaG93Ig&_c=R1VN&cl=5&cr=5&s=0&l=10): GUM guidelines say [an advcl containing "how" should always have "how" as an advmod of the clausal head](http://corpling.uis.georgetown.edu/wiki/doku.php?id=gum:dependencies#mark_vs_advmod), but many GUM sentences have "how" as the clausal head

**Comment by lgessler** [comment]
Going to post some other misc. things I caught along the way here... GUM_whow_flirt has an obviously wrong acl:relcl around token 300:

![image](https://user-images.githubusercontent.com/7650725/95778530-4cea8e00-0c96-11eb-869d-ea84cee77555.png)

**Comment by lgessler** [comment]
(If you can let me know how to fix these in a PR, I'd be happy to. I think I ought to just modify the .conllu file under `_build/src/dep` and submit a PR against the dev branch, right?)

**Comment by amir-zeldes** [comment]
In this case actually the GUM guidelines in the wiki are out of date (so that's the thing to fix), see this discussion:

https://github.com/UniversalDependencies/UD_English-EWT/issues/88

This has a long history in Stanford Dependencies, but basically the latest decision was:

  * Use `advmod` if it's an interrogative pronoun in an actual question
  * Use `mark` if it's introducing a subordinate clause (so that 'when' behaves like 'if', since we never want 'if' to be ADV+advmod - therefore all of these are mark when they are upos=SCONJ)

**Comment by amir-zeldes** [comment]
And yes, feel free to PR against dev in the src/ folders! Could you also update the wiki to reflect the guidelines above? You can ignore the upos part since annotators only need to worry about xpos, which is WRB either way.

**Comment by amir-zeldes** [comment]
nvm, just took care of the guidelines

**Comment by nschneid** [comment]
> In this case actually the GUM guidelines in the wiki are out of date (so that's the thing to fix), see this discussion:
> 
> [UniversalDependencies/UD_English-EWT#88](https://github.com/UniversalDependencies/UD_English-EWT/issues/88)
> 
> This has a long history in Stanford Dependencies, but basically the latest decision was:
> 
>   * Use `advmod` if it's an interrogative pronoun in an actual question
> 
>   * Use `mark` if it's introducing a subordinate clause (so that 'when' behaves like 'if', since we never want 'if' to be ADV+advmod - therefore all of these are mark when they are upos=SCONJ)

@amir-zeldes, TBC a subordinate clause could be an `advcl` or `ccomp`, right? Are you saying that _when_ introducing a clause is always `SCONJ` and `mark`? I can't follow the back and forth in [UniversalDependencies/UD_English-EWT#88](https://github.com/UniversalDependencies/UD_English-EWT/issues/88).

**Comment by amir-zeldes** [comment]
Oh certainly, "when" can be advmod in a question. Here are the different constructions as I understand them (and as they should be annotated in GUM, AFAIK):

  * When/ADV/advmod did you arrive/VERB/root? (question)
  * Call me when/SCONJ/mark you arrive/VERB/advcl. (subordinate advcl)
  * Tell me when/SCONJ/obj you arrived/VERB/acl:relcl. (free relative)
