### ISSUE TITLE
Inconsistent annotation of quotes

### ISSUE THREAD

**Issue by reckart** [amir-zeldes/gum#7]
There seem to be some inconsistencies about the annotation of quotes, e.g.

**Double quotes**
```
"	_	``	``   <= this seems ok, others not
"	_	''	''   <= also ok as Amir pointed out
"	_	'	'
"	_	0	0
```

**Single quotes**
```
'	_	``	``   <= this seems ok, others not
'	_	"	''
'	_	"	"
'	_	'	'
'	_	POS	POS
```

**Comment by amir-zeldes** [comment]
I think some of these are OK:
  * Tagging a double or single quote with two single quotes as the tag: `''` - this is used when distinguishing tags for opening and closing quotation marks. I believe the vanilla PTB standard also supports this, though I've noticed the default Stanford tagger model doesn't do it (though the parser training model includes it)
  * POS - this can be a possessive genitive apostrophe for plural nouns, e.g. the kids **'** toys

The rest are errors. I've made a new conll module for the GUM Build Bot (still a WIP), which should take care of these and some other errors. It also adds speaker information and sentence types as comments to each sentence. Take a look at the dev branch, I'm letting it sit there for a bit while I work on the rest of the build bot. Thanks again for your feedback!

**Comment by reckart** [comment]
Right, `"   _   ''  ''` is also valid for closing quotes - sorry.

I thought that POS can also be the possessive apostrophe, but checking the actual data, it seems that proper quotes have been mistagged as POS specifically in one file `GUM_whow_languages.conll10`:

```
13	language	_	NN	NN	_	9	pobj	_	_
14	like	_	IN	IN	_	13	prep	_	_
15	'	_	'	'	_	0	punct	_	_
16	Victory	_	NP	NP	_	14	pobj	_	_
17	'	_	POS	POS	_	0	punct	_	_
18	or	_	CC	CC	_	16	cc	_	_
19	'	_	POS	POS	_	0	punct	_	_
20	Great	_	NP	NP	_	21	nn	_	_
21	Language	_	NP	NP	_	16	conj	_	_
22	'	_	POS	POS	_	0	punct	_	_
```

**Comment by amir-zeldes** [comment]
Yes, I see, these are genuine tagging errors that were missed. They should be updated in the XML file, which I'll do now, and they'll propagate in the next update. I realize now that we're going to need a little guide for where to update what (e.g. update POS tags only in the XML files). Or else modify the build bot to realize which files have been updated more recently and propagate in all directions needed, but that could be pretty complicated due to conflicts. I'll make another issue.

**Comment by reckart** [comment]
Such a guide would be very helpful :)
