### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.feature_extraction'

### ISSUE THREAD

**Issue by katherine-atwell** [amir-zeldes/gum#70]
When I ran process_reddit.py, I was able to get the Reddit data fine. But when I ran build_gum.py, I got the following:

`====================
Validating files...
====================

Found reddit source data
Including reddit data in build
o Found 148 documents
o File names match
o Token counts match across directories
o 148 documents pass XSD validation                              
                                        Traceback (most recent call last):
  File "_build/build_gum.py", line 95, in <module>
    from utils.repair_rst import fix_rst
  File "/Users/katherineatwell/cs-programs/research/resources/gum/_build/utils/repair_rst.py", line 6, in <module>
    from .rst2dep import make_rsd
  File "/Users/katherineatwell/cs-programs/research/resources/gum/_build/utils/rst2dep.py", line 14, in <module>
    from .feature_extraction import ParsedToken
ModuleNotFoundError: No module named 'utils.feature_extraction'`

I looked for a feature_extraction file in utils and couldn't find it, so I'm not sure what to do.

Thanks!

**Comment by lgessler** [comment]
Hi Katherine, not sure if this'll solve the issue but I glanced at [the `dev` branch](https://github.com/amir-zeldes/gum/tree/dev) and it looks like [`feature_extraction.py` exists there](https://github.com/amir-zeldes/gum/blob/dev/_build/utils/feature_extraction.py). You could try to either copy that file into your current utils file or checkout the `dev` branch and try again.

**Comment by amir-zeldes** [comment]
Thanks for reporting - I've merged `feature_extraction.py` from dev in #72 but note that the current state of master is ahead of the stable v6.1 release and not yet quite ready for v6.2. 

We are expecting a new release very soon in coordination with the upcoming release of Universal Dependencies, which will add many corrections and improvements, especially a complete overhaul of the entity/coreference annotation layers, so it may be worth checking back in a week or two for the new stable version.

**Comment by katherine-atwell** [comment]
Thank you so much! I was able to build the corpus after a couple quick fixes
