### ISSUE TITLE
Plain text paragraphs

### ISSUE THREAD

**Issue by katherine-atwell** [amir-zeldes/gum#73]
Is there any way to access the plain text paragraphs for the corpus data? Or would it be best to reconstruct this data using the XML files?

**Comment by lgessler** [comment]
You'll have to reconstruct it from the XML. You can either parse it with something like [etree](https://docs.python.org/3/library/xml.etree.elementtree.html) or iterate through the file's lines – the latter's probably easier for this. Note that if you care about the original whitespace, you should look out for the `<w>` element, which surrounds tokens that were originally spelled without whitespace between them ([example](https://github.com/amir-zeldes/gum/blob/master/xml/GUM_fiction_pixies.xml#L822#L842)).

**Comment by katherine-atwell** [comment]
Perfect, thank you so much!

**Comment by amir-zeldes** [comment]
Just to clarify about `<w>` - those are only used for **non-trivial** things written together, which could be either way, for example `a / b` versus `<w>a/b</w>`. For trivial contractions, like "can't", "you'll" etc. there is no <w> tag, but the information is reconstructed by the build bot based on a closed list. The best way to get original plain text is to look at the .conllu files, which have an attribute `SpaceAfter=No`, as well as the reconstructed text of each sentence in a sentence-based comment.

**Comment by amir-zeldes** [comment]
And one other thing: `<p>` tags only appear if there is no other block-level element that implies them (a bit like HTML). So if you have `<head>` or `<list>` there will be no accompanying <p>, except in unusual situations (e.g. a list `<item>` containing multiple paragraphs will contain those `<p>` elements, if not it is understood that the `<item>` contained a single paragraph).

**Comment by katherine-atwell** [comment]
Sounds good! In the case of an <list> inside a <p>, would each item inside the list still be considered its own paragraph break?

**Comment by amir-zeldes** [comment]
Yes, list items and lists are implicitly always a block element, so you won't get another `<p>` anywhere there. Here are two examples, one with single paragraph items and one with multi-paragraph items. The logic is similar to HTML:

```
<p>Some previous paragraph before the list</p>
<list type="unordered">
<item>First item, which is a block element, so it needs no p tag</item>
<item>Second item, the same</item>
</list>
<p>Next paragraph after the list</p>
```

Multi-paragraph example
```
<p>Some previous paragraph before the list</p>
<list type="unordered">
<item>
     <p>First item, first paragraph (since this bullet point actually contains two paragraphs!)</p>
     <p>Second paragraph of first item</p>     
</item>
<item>Second item, has only one paragraph, so no p - it is assumed that each item is at least a single paragraph block</item>
</list>
<p>Next paragraph</p>
```

BTW we have also used these for RST parsing, and have some code enriching EDUs with XML properties in the GUM build bot. If you look at the RST dependencies output you can see it, for example line 1 here is marked as `heading` and line 2 is `para`, indicating this EDU opens a new paragraph:

https://github.com/amir-zeldes/gum/blob/master/rst/dependencies/GUM_whow_ballet.rsd#L1-L2

It definitely helps to have these attributes, see [this paper](https://www.aclweb.org/anthology/2020.lrec-1.648.pdf) for some results.
