### ISSUE TITLE
Varying analyses of "including"

### ISSUE THREAD

**Issue by lgessler** [amir-zeldes/gum#75]
[Instances of "including" in GUM](https://corpling.uis.georgetown.edu/annis/#_q=ImluY2x1ZGluZyIg&_c=R1VN&cl=5&cr=5&s=0&l=10) vary in whether they're treated as `case(Nchild, including)` or `acl(Nparent, including)`, or something else.

I'm not sure what to think of whether this is more clausal or prepositional. A clausal analysis seems best wherever there's a prototypical agent as its parent or as the subject of its parent:

1. [The man [including examples in his GitHub issue]] wrote a few paragraphs
2. The man [wrote a few paragraphs [including examples in his GitHub issue]]

Seems odder to me somehow when this is not the case since the basic sense of "including" would seem to require a volitional agent. The clausal analysis seems questionable in (3–5) to me.

3. Three birds were visible on the fence including a robin, sparrow, and crow.
4. Three birds including a robin sparrow and crow were visible on the fence.
5. This pattern holds true for many workers  including assembly line laborers who build cars, stylists who cut hair, and doctors who perform heart surgery.

Is this a case of genuine ambiguity or should these analyses be unified? Note that [PTB POS guidelines say anything ending in _-ing_ or _-ed_ is never IN](https://catalog.ldc.upenn.edu/docs/LDC99T42/tagguid1.pdf#page=13), so strict consistency with XPOS would always require a clausal analysis

**Comment by lgessler** [comment]
I see that [according to is treated as a fixed expression in the guidelines](http://corpling.uis.georgetown.edu/wiki/doku.php?id=gum:dependencies&rev=1605209779#list_of_fixed_expressions) and that `case(X, according)` for all instances of "according to" ([except one](https://corpling.uis.georgetown.edu/annis/#_q=L1tBYV1jY29yZGluZy8gLiAidG8iIAomICMxIC0-ZGVwW2Z1bmM9Im9ibCJdIHRvaw&_c=R1VN&cl=5&cr=5&s=0&l=10))

**Comment by amir-zeldes** [comment]
Your split of cases makes sense to me, and looking at EWT it is mirrored there as well: "including" as a verb is analyzed syntactically, with clausal readings etc. The prepositional interpretation (though xpos is VBG as you pointed out) is always the desired analysis IMO whenever it is substitutable by "such as".

The "according to" exception is definitely wrong, will fix.

**Comment by nschneid** [comment]
Worth revisiting in light of the decision that a VERB can serve as `case` or `mark`.

**Comment by amir-zeldes** [comment]
more in 7b17e98
