### ISSUE TITLE
Various issues in xml and dep

### ISSUE THREAD

**Issue by lgessler** [amir-zeldes/gum#76]
See log here: https://gist.github.com/lgessler/bb5a1d224c476c8c7340b09818233178

This log was made using [a post-build validation script](https://github.com/lgessler/gum/commit/d120df10dd8491dcde293ea07fa70c4d9270ff9c) I made--happy to open a PR if you want it

**Comment by amir-zeldes** [comment]
Most of these specific issues should be resolved now. For fixed note that the build bot already checks a list here:

https://github.com/amir-zeldes/gum/blob/dev/_build/utils/validate.py#L622

As well as back pointing fixed and conj (but not flat and goeswith, I just added those!)

In general if you want to add production validations, this would be the place. I'm not sure about the contiguous flat, for some of those I can't think of a better way to do the tree, so maybe the 'flatness' begins after the first token takes any relevant complex modifiers? If you have a better tree suggestion for those, let me know!
