### ISSUE TITLE
Possibly inconsistent lemmatization of longer

### ISSUE THREAD

**Issue by AngledLuffa** [amir-zeldes/gum#83]
Someone's life isn't much longer, lemma is "long":

```
# text = Alternatively, if life has not been good to you so far, (and considering your current situation this seems more likely) consider how lucky you are that it will not be troubling you much longer.
38      longer  long    ADV     RBR     Degree=Cmp      35      advmod  _       SpaceAfter=No
```

but cleaning things takes longer, lemma is "longer":

```
# text = The gingerbread batter bowl could wait a day, even though it would take longer to clean tomorrow.
15      longer  longer  ADV     RBR     Degree=Cmp      14      advmod  _       _
```

People's rides are longer, lemma is "longer":

```
# text = This makes everyone’s ride on the elevator longer, if only for a few seconds.
9       longer  longer  ADJ     JJR     Degree=Cmp      2       xcomp   _       SpaceAfter=No
```

but someone's limbs are longer, lemma is "long":

```
# text = Longer limbs are expected to experience larger bending and torsional moments, so the fact that experimental animals had longer femora suggests that limb verticalization reduces these moments by orienting the bone more parallel to the GRF line of action.
1       Longer  long    ADJ     JJR     Degree=Cmp      2       amod    _       Discourse=cause:65->69|Entity=(object-112
20      longer  long    ADJ     JJR     Degree=Cmp      21      amod    _       Entity=(object-115
```

**Comment by amir-zeldes** [comment]
Thanks for reporting this and #83 - I can fix both. 

I noticed you are making PRs for EWT and just wanted to point out that if you would like to make PRs into GUM, which would be great, those happen in the GUM source repo (amir-zeldes/gum), which has the data in multiple formats and is a bit more complicated than the UD version. See here for more details if you're interested: https://corpling.uis.georgetown.edu/gum/build.html

**Comment by AngledLuffa** [comment]
Great, thanks!

I will go through that PR process if relevant.  For now, a few people had noticed that the -er and -est lemmas in EWT were not labeled as expected, so I was looking to match the GUM standard for those.  Just happened to notice a few weird labels on the way.

**Comment by amir-zeldes** [comment]
OK, thanks - this will propagate to UD automatically for the next release.
