### ISSUE TITLE
Adjunct relative that-clause

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#87]
Per UniversalDependencies/UD_English-EWT#173, the sentence

* You know what I think, I think the first time __that__ it does the card mode, it takes a long time.

correctly tags "that" as `SCONJ`, but it has `WDT`, `PronType=Rel` and an enhanced `ref` dependency—these should be reserved for heads that fill a role in the embedded predicate.

**Comment by amir-zeldes** [comment]
Thanks for spotting this, the parse is correct but the POS tag was wrong. Will fix.
