### ISSUE TITLE
"along with"

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#88]
In e.g.

- He arrived along with a few friends.
- Along with the cake mix, I bought some candles.

EWT would treat "along" and "with" as sister ADPs, both attaching as `case`. Since "along" by itself can be a preposition (*walk along the river*), I think this makes sense.

Note that the verbal idioms "go along (with)" 'follow', "get along (with)", etc. are different.

**Comment by amir-zeldes** [comment]
I'm not so sure about this - I would interpret "along with" the same as "together with", so if they are sisters I think they should be ADV + ADP. If you think it's a fixed expression that would be different (then it's one big preposition), but I actually think it's pretty compositional (though certainly conventional/entrenched)

**Comment by nschneid** [comment]
"Along with", "across from", "together with", "apart from", "away from", "next to" are all similar constructions as far as I can tell—e.g. they can substitute for "beside" in "I am sitting beside my cousin". (Plain "with" can as well; "from" and "to" cannot.)

I wouldn't describe any of them as fully compositional (in this sense at least). They are not fully opaque in meaning, but these bigrams have to be learned to be used correctly.

The difference between "along"/"across" and "together"/"apart"/"away"/"next" is that the former can be transitive, which in UD could be considered relevant for adopting its canonical UPOS of ADP even in these multiword combinations. That seems to be what EWT does, anyway, for "along with" and "across from".

The sister `case` ADP+ADP analysis applies to several multiword prepositiony things: "out of", "off of", "as for", "as in", "as with", "except for" in EWT. Would would be the principle for treating "along with" differently?

OTOH we have "in between" and "as to" under [`fixed`](https://universaldependencies.org/en/dep/fixed.html). Why?

P.S. Some cases of "next to" in EWT are double ADP/case, while others aren't—apparently inconsistent.

**Comment by nschneid** [comment]
(Existing issue on "next to": UniversalDependencies/docs#496)

**Comment by nschneid** [comment]
Ha turns out this was UniversalDependencies/UD_English-GUM#1

**Comment by amir-zeldes** [comment]
Yes, well spotted - I see I already expressed my misgivings about the double case analysis over there. I don't think "out of" is the same as "along with", since we can leave "along" out, but not so with "out". Compare:

  * I jumped out of the box. * I jumped of the box.
  * Sweat the garlic along with the onion. Sweat the garlic with the onion.

On top of that, while "along" has a prepositional version as well, words like "together" do not: "* I did it together Kim". I would prefer to treat "along" here as an adverb on the same level as together. BTW "out of" and "off of" are not sister cases in GUM, they are `fixed`, which I think is the right analysis for them (even more so given the prevalence of univerbized "outta").

**Comment by nschneid** [comment]
I suspect "along"/"together" serve to disambiguate the "with", which by itself is highly ambiguous. From that perspective we could say they are modifying "with" (in a collocation). I wouldn't hate `advmod(with/ADP along/ADV)`, though I think `fixed` would also be justified because the expression is lexicalized ("along" and "together" do not modify prepositions other than "with", nor does "with" accept other sense-specific modifiers that I know of; contrast "right" and "just", which can modify PPs broadly).

Maybe we should abandon the sister `case` analysis for things like "out of", which never made sense to me either TBH.

**Comment by amir-zeldes** [comment]
Yes, by all means - I think "out of" and "off of" should be in the fixed list (I somehow thought they already were in EWT)

If you like along/ADV, then I think that's nicer because it keeps it together with "together" (which is definitely not ADP morphosyntactically, and behaves very much the same here). As for attachment, I'd prefer to attach it to the lexical head using the typical UD "it modifies the whole thing" logic, because dependents of `case` are something we avoid in general across the board.

**Comment by nschneid** [comment]
(OK if I wanted to make the argument for sister `case` with "out of", it would be based on the CGEL argument that "out" is a preposition whether or not it is transitive, and many prepositions take of-PP complements. So: _I jumped out. / I jumped out the door. / I jumped out of the room._ would all have "out" as a preposition differing only in complementation. Then the structure is [out [of [the room]]], but because UD wants `case` to be headed by a content word, "out" and "of" attach as sisters.

All in all, though, the foundations of this argument are rather different from the assumptions about structure that UD makes, and `fixed(out, of)` is more intuitive from a dependency perspective.)

**Comment by nschneid** [comment]
> dependents of `case` are something we avoid in general across the board.

Oh right, I found 2 examples of "just" attaching to "over"/"under" as `advmod` but those must be errors.

I must say I don't love an analysis where "together" and "along" are sister to "with", because if anything they are modifying "with" and not the with-PP as a whole...it does follow from "together with" that you are with someone and the two of you are together, but that doesn't work for "along":

* I sat together with my cousin. I sat with my cousin. We sat together.
* I sat along with my cousin. I sat with my cousin. *We/I sat along.

And as I mentioned above, these two bigrams have to be learned as special cases, like how "in between" (when transitive) is an alternative to plain "between". So I think `fixed` is the most straightforward solution.

**Comment by nschneid** [comment]
@amir-zeldes are you able to transfer this issue to the main UD docs repo? Just realized that others who may want to weigh in probably aren't following this issue tracker.

**Comment by amir-zeldes** [comment]
No, it looks like I can only transfer to repos in the same organization... But I don't think this is particularly controversial (or feel free to open on on UD_English-XYZ). 

I will never feel comfortable using the term "intransitive preposition" - prepositions, by their very name, imply being "before something else they need". If anything, I think it makes more sense to think of prepositions as transitive adverbs! And this is, at least for IE languages, also what actually happened historically, as best we know.

In any case, the UD habit of attaching function words to the lexical kernel of the phrase in which they are modifiers is pretty established, so I think opening that can of worms can only bring trouble (though FWIW I feel the same, I used to be very sad about being unable to do dependents of prepositions, I guess I just got used to it). This is really not different from negation on VP with aux though, where my intuition is definitely that the aux is being negated, especially for modals, where the semantic negation hierarchy seems extra clear. I guess it's the price we pay for that nice lexicocentrism, and at least it's fairly predictable.

**Comment by nschneid** [comment]
The double case analysis was also raised as UniversalDependencies/UD_English-EWT#38.

**Comment by amir-zeldes** [comment]
True. This must have been around the time we adopted `fixed` for "out of" in GUM... So are we in agreement? Is there anything we need to change in GUM actually?

**Comment by nschneid** [comment]
This feels like a significant guidelines change for which others should have the opportunity to weigh in, so I've opened the above thread.

**Comment by amir-zeldes** [comment]
OK, I'll close this one for now then, since there is no change to be made yet and discussion can continue on the UD repo.
