### ISSUE TITLE
Pre-possessive modifiers in NPs

### ISSUE THREAD

**Issue by nschneid** [amir-zeldes/gum#90]
I was exploring special cases where something could precede a possessive in an NP: http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=611c22ca1ede8

Some of these appear to be determiner misattachments, e.g. "the nation's past" should be `det(nation, the)`.

(In cases where the possessive is lexicalized it is legitimate: e.g. "my California Driver's license".)

**Comment by nschneid** [comment]
Grouped by deprel: http://match.grew.fr/?corpus=UD_English-GUM@dev&custom=611d189dc0b7f&clustering=e.label

**Comment by amir-zeldes** [comment]
Thanks for reporting, the ones that are genuine errors should be fixed now upstream, will propagate for next release
