### ISSUE TITLE
Tokenization error

### ISSUE THREAD

**Issue by yilunzhu** [amir-zeldes/gum#96]
GUM_reddit_card, sent_id=2, be hind -> behind

**Comment by amir-zeldes** [comment]
It's that way in the original:

https://www.reddit.com/r/personalfinance/comments/cmqrwo/be_careful_what_you_say_in_public/?utm_source=share&utm_medium=web2x&context=3

Both standard LDC English corpus practices and UD guidelines keep such split tokens apart, but note that we have a `goeswith` deprel (see [goeswith](https://universaldependencies.org/u/dep/goeswith.html) and a GUM TEI `<sic>` tag in the XML data to indicate the error.
